require: rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/IndentationConsistency:
  EnforcedStyle: rails
