require: rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/environments/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/IndentationConsistency:
  EnforcedStyle: rails

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'FactoryBot.define', 'factory']
